### ISSUE TITLE
Fix host reservation creation on updating existing event

### ISSUE THREAD

**Issue by mrpresidentjk** [mrpresidentjk/livelobby#43]
A bug exists where a reservation for the host initial party is created when updating an event object. This is due to the `save()` method

**Comment by marcustessema** [comment]
This should be solved by Issue-42.

**Comment by marcustessema** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Event Details Component - Release Version MVP Stage II](https://trello.com/c/qMYOsixp/105-event-details-component-release-version-mvp-stage-ii)
